#!/usr/bin/env node
// Generates examples/specimen.html — every token rendered at actual size, with
// contrast ratios measured by the same maths the validator uses.
//
// The point of a specimen is to be checkable by eye. A ratio printed here and a
// ratio enforced in build.mjs come from lib/contrast.mjs, so there is one answer
// to "does this pass" rather than two that can disagree.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ratio } from "../lib/contrast.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const T = JSON.parse(readFileSync(join(ROOT, "tokens.json"), "utf8"));
const CSS = readFileSync(join(ROOT, "build/tokens.css"), "utf8");

const real = (o) => Object.keys(o).filter((k) => !k.startsWith("_"));
const hex = (n) => T.color[n].value;
const r2 = (n) => n.toFixed(2);
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const SAMPLE = "Find the pattern. Build with conviction.";
const PARA =
  "Most companies scale their problems. We help founders find the logic underneath the business, then build brand, product and systems from it. The organizations that last were never invented — they were discovered, a pattern drawn out and then built upon.";

// ── ramps ─────────────────────────────────────────────────────────────────────
const rampGroups = [...new Set(Object.values(T.color).map((c) => c.group))];
const ramps = rampGroups.map((g) => {
  const names = Object.keys(T.color).filter((n) => T.color[n].group === g);
  const swatches = names.map((n) => {
    const c = T.color[n];
    const onLight = ratio(hex(n), hex("stone-50"));
    const onDark = ratio(hex(n), hex("stone-900"));
    return `<div class="sw">
      <div class="chip" style="background:${c.value}"></div>
      <div class="meta">
        <b>${n}</b>${c.name ? `<i>${c.name}</i>` : ""}
        <code>${c.value}</code>
        <span>on canvas ${r2(onLight)} &middot; on ink ${r2(onDark)}</span>
        <em>${esc(c.use)}</em>
      </div>
    </div>`;
  }).join("");
  return `<h3 class="type-heading-sm">${g}</h3><div class="ramp">${swatches}</div>`;
}).join("");

// ── type roles ────────────────────────────────────────────────────────────────
const roles = real(T.role).map((name) => {
  const r = T.role[name];
  const size = T.scale.size[r.size];
  const fg = hex(T.semantic[r.color]);
  const measured = ratio(fg, hex("stone-50"));
  const big = size >= 24 || (size >= 19 && T.weight[r.weight] >= 700);
  const need = big ? 3.0 : 4.5;
  const pass = measured >= need;
  const text = r.casing === "uppercase" ? "Approach" : size >= 27 ? SAMPLE : PARA;
  return `<div class="role">
    <div class="rmeta">
      <b>${name}</b>
      <span>${size}px / ${T.scale.leading[r.leading]} / ${T.scale.tracking[r.tracking]} / ${T.weight[r.weight]}</span>
      <span>${r.cut} cut &middot; ${T.semantic[r.color]}</span>
      <span class="${pass ? "ok" : "no"}">${r2(measured)}:1 &middot; needs ${need} &middot; ${pass ? "AA" : "FAIL"}</span>
    </div>
    <div class="rsample"><p class="type-${name}">${text}</p></div>
  </div>`;
}).join("");

// ── semantic table ────────────────────────────────────────────────────────────
const semantic = real(T.semantic).map((k) => {
  const l = T.semantic[k], d = T.semanticDark[k] ?? l;
  return `<tr>
    <td><code>--color-${k}</code></td>
    <td><span class="dot" style="background:${hex(l)}"></span>${l}</td>
    <td><span class="dot" style="background:${hex(d)}"></span>${d}${d === l ? " <i>(same)</i>" : ""}</td>
  </tr>`;
}).join("");

// ── spacing ───────────────────────────────────────────────────────────────────
const twMap = { 1: 1, 2: 2, 3: 3, 4: 4, 5: 6, 6: 8, 7: 12, 8: 16, 9: 24, 10: 32, 11: 48 };
const spacing = real(T.space).map((k) => `<div class="sp">
    <span class="spl"><b>space-${k}</b> ${T.space[k]}px <i>tw ${twMap[k]}</i></span>
    <span class="spb" style="width:${T.space[k]}px"></span>
  </div>`).join("");

// ── radii, shadows, motion ────────────────────────────────────────────────────
const radii = real(T.radius).map((k) => `<div class="tile">
    <div class="rbox" style="border-radius:${T.radius[k]}"></div><b>radius-${k}</b><code>${T.radius[k]}</code>
  </div>`).join("");

const shadows = real(T.shadow).map((k) => `<div class="tile">
    <div class="sbox" style="box-shadow:${T.shadow[k]}"></div><b>shadow-${k}</b>
  </div>`).join("");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Archetype — specimen</title>
<!-- GENERATED by scripts/specimen.mjs from tokens.json. Do not edit by hand. -->
<style>
${CSS}
</style>
<style>
  *{box-sizing:border-box}
  body{margin:0;background:var(--color-background-primary);color:var(--color-text-secondary)}
  .wrap{max-width:var(--container-site);margin:0 auto;padding:var(--space-8) var(--space-6)}
  header{border-bottom:1px solid var(--color-border-strong);padding-bottom:var(--space-6);margin-bottom:var(--space-8)}
  .mark{color:var(--color-text-primary);display:block;height:72px;margin-bottom:var(--space-5)}
  .mark svg{height:100%;width:auto;display:block}
  section{margin:var(--space-9) 0}
  h2{font:var(--type-heading-lg);letter-spacing:var(--tracking-heading-lg);color:var(--color-text-primary);
     border-bottom:1px solid var(--color-border-subtle);padding-bottom:var(--space-3);margin:0 0 var(--space-6)}
  h3{margin:var(--space-6) 0 var(--space-3);text-transform:capitalize}
  code{font:var(--type-ui-sm);font-family:var(--font-mono);color:var(--color-text-emphasis)}

  .ramp{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:var(--space-3)}
  .sw{display:flex;gap:var(--space-3);border:1px solid var(--color-border-subtle);padding:var(--space-3)}
  .chip{width:56px;height:56px;flex:0 0 56px;border:1px solid var(--color-border-strong)}
  .meta{display:flex;flex-direction:column;gap:2px;min-width:0}
  .meta b{font:var(--type-ui);font-weight:500;color:var(--color-text-primary)}
  .meta i{font:var(--type-caption);font-style:normal;color:var(--color-text-tertiary)}
  .meta code{font-size:12px}
  .meta span{font:var(--type-caption);color:var(--color-text-tertiary)}
  .meta em{font:var(--type-caption);font-style:normal;color:var(--color-text-secondary);margin-top:2px}

  .role{display:grid;grid-template-columns:220px 1fr;gap:var(--space-5);padding:var(--space-5) 0;
        border-top:1px solid var(--color-border-subtle);align-items:baseline}
  .rmeta{display:flex;flex-direction:column;gap:3px}
  .rmeta b{font:var(--type-ui);font-weight:500;color:var(--color-text-primary)}
  .rmeta span{font:var(--type-caption);color:var(--color-text-tertiary)}
  .rmeta .ok{color:var(--color-accent-primary)}
  .rmeta .no{color:var(--color-accent-warm);font-weight:500}
  .rsample p{margin:0;max-width:var(--container-measure)}

  table{width:100%;border-collapse:collapse}
  td,th{text-align:left;padding:var(--space-2) var(--space-3);border-bottom:1px solid var(--color-border-subtle);
        font:var(--type-ui-sm)}
  th{color:var(--color-text-primary);font-weight:500}
  .dot{display:inline-block;width:12px;height:12px;margin-right:8px;vertical-align:-1px;
       border:1px solid var(--color-border-strong)}
  td i{color:var(--color-text-tertiary);font-style:normal}

  .sp{display:flex;align-items:center;gap:var(--space-4);padding:5px 0}
  .spl{font:var(--type-caption);color:var(--color-text-tertiary);width:190px;flex:0 0 190px}
  .spl b{color:var(--color-text-primary)}
  .spl i{font-style:normal;color:var(--color-text-disabled)}
  .spb{height:14px;background:var(--color-accent-primary);display:block}

  .tiles{display:flex;flex-wrap:wrap;gap:var(--space-5)}
  .tile{display:flex;flex-direction:column;gap:6px;align-items:flex-start}
  .tile b{font:var(--type-caption);color:var(--color-text-primary)}
  .rbox{width:88px;height:64px;background:var(--color-background-secondary);border:1px solid var(--color-border-strong)}
  .sbox{width:88px;height:64px;background:var(--color-background-primary);border:1px solid var(--color-border-subtle)}

  .themes{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-5)}
  .panel{padding:var(--space-6);background:var(--color-background-primary);border:1px solid var(--color-border-subtle)}
  .panel .eb{font:var(--type-eyebrow);letter-spacing:var(--tracking-eyebrow);text-transform:uppercase;
             color:var(--color-text-secondary);display:block;margin-bottom:var(--space-3)}
  .panel h4{font:var(--type-heading-md);color:var(--color-text-primary);margin:0 0 var(--space-3)}
  .panel p{font:var(--type-body);color:var(--color-text-secondary);margin:0 0 var(--space-5)}
  .btn{font:var(--type-ui);display:inline-block;padding:10px 18px;border-radius:var(--radius-sm);
       background:var(--color-action-primary-bg);color:var(--color-action-primary-fg);border:0;cursor:pointer}
  .btn.ghost{background:transparent;color:var(--color-action-secondary-fg);
             border:1px solid var(--color-action-secondary-border)}
  .rule{height:1px;background:var(--color-border-hairline-warm);margin:var(--space-5) 0;width:56px}
  footer{border-top:1px solid var(--color-border-strong);margin-top:var(--space-9);padding-top:var(--space-5)}
  @media (max-width:720px){.role,.themes{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <span class="mark">${readFileSync(join(ROOT, "assets/logo/archetype-mark.svg"), "utf8").trim()}</span>
    <h1 class="type-display-md">Specimen</h1>
    <p class="type-body">Every token at actual size. Generated from <code>tokens.json</code> — ${T.meta.name} v${T.meta.version}. Contrast ratios are measured by the same maths the build enforces.</p>
  </header>

  <section>
    <h2>Color</h2>
    <p class="type-body-sm">Target ratio ${Math.round(T.palette.ratio.stone * 100)}% stone, ${Math.round(T.palette.ratio.verdigris * 100)}% verdigris, ${Math.round(T.palette.ratio.bronze * 100)}% bronze. Ratios shown against <code>stone-50</code> and <code>stone-900</code>.</p>
    ${ramps}
  </section>

  <section>
    <h2>Semantic layer</h2>
    <p class="type-body-sm">What product code reaches for. Each is a reference, so the dark column re-points it without redefining a hex.</p>
    <table><thead><tr><th>Token</th><th>Light</th><th>Dark</th></tr></thead><tbody>${semantic}</tbody></table>
  </section>

  <section>
    <h2>Type</h2>
    <p class="type-body-sm">${real(T.role).length} roles. Display cut at ${T.rules.opticalBoundary.displayMin}px and above, text cut at ${T.rules.opticalBoundary.textMax}px and below, nothing sans between. Rendered in proxy faces — ${T.font.proxy.display.split(",")[0]} and ${T.font.proxy.serif.split(",")[0].replace(/"/g, "")} — so line breaks are arbitrary and the two sans optical cuts render identically.</p>
    ${roles}
  </section>

  <section>
    <h2>Spacing</h2>
    <p class="type-body-sm">Every step is an exact multiple of Tailwind's 4px base, so the utility scale already expresses all of them.</p>
    ${spacing}
  </section>

  <section>
    <h2>Radius and elevation</h2>
    <p class="type-body-sm">Sharp by default. Pills are reserved for status badges and radio controls. Cards rest on a border, never a shadow.</p>
    <div class="tiles">${radii}</div>
    <div class="tiles" style="margin-top:var(--space-6)">${shadows}</div>
  </section>

  <section>
    <h2>In place</h2>
    <p class="type-body-sm">The same markup in both themes. Nothing changes but the <code>data-theme</code> attribute.</p>
    <div class="themes">
      <div class="panel">
        <span class="eb">Approach</span>
        <h4>Find the pattern.</h4>
        <p>Most companies scale their problems. We help founders find the logic underneath the business.</p>
        <div class="rule"></div>
        <button class="btn">Start a project</button>
        <button class="btn ghost">Read the notes</button>
      </div>
      <div class="panel" data-theme="dark">
        <span class="eb">Approach</span>
        <h4>Find the pattern.</h4>
        <p>Most companies scale their problems. We help founders find the logic underneath the business.</p>
        <div class="rule"></div>
        <button class="btn">Start a project</button>
        <button class="btn ghost">Read the notes</button>
      </div>
    </div>
  </section>

  <footer>
    <p class="type-caption">Generated by <code>npm run specimen</code>. Do not edit this file — regenerate it.</p>
  </footer>
</div>
</body>
</html>
`;

mkdirSync(join(ROOT, "examples"), { recursive: true });
writeFileSync(join(ROOT, "examples/specimen.html"), html);
console.log(`Wrote examples/specimen.html — ${real(T.role).length} roles, ${Object.keys(T.color).length} colors.`);
